    # Rafael Dutra
sudo: required

services:
  - docker

stages:
  - run
  - tag
  - publish

jobs:
  include:
    - stage: run
      before_script:
        - docker --version
      script:
        - |
          docker run \
          -itd \
          -v $(pwd)/site:/src \
          -p 1313:1313 raffaeldutra/docker-gohugo /gohugo.sh -s config-docker.toml
    - stage: tag
      script:
        - git config --local user.name "Deploy FOSSDay"
        - git config --local user.email "fossday@fossday.org"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
        - git push --tags
    - stage: publish
      script:
        - |
          docker run \
          --rm \
          -v $(pwd)/site:/src \
          -v $(pwd)/public:/src/public \
          raffaeldutra/docker-gohugo /gohugo.sh -p config-docker.toml
      deploy:
        name: "FOSS Team Deployment"
        provider: pages
        local_dir: public
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        verbose: true
        target_branch: master
        on:
          tags: true
        fqdn: fossday.org
