# Rafael Dutra
sudo: required

services:
  - docker

stages:
  - run
  - test
  - deploy

jobs:
  include:
    - stage: run
      before_script:
        - docker --version
      script:
        - |
          docker run \
          -itd \
          -v $(pwd)/site:/src \
          -p 1313:1313 raffaeldutra/docker-gohugo /gohugo.sh -s config-docker.toml
    - stage: test
      script:
        - curl -s http://localhost:1313 | grep i.imgur.com
    - stage: deploy
      script:
        - |
          docker run \
          --rm \
          -v $(pwd)/site:/src \
          -v $(pwd)/public:/src/public \
          raffaeldutra/docker-gohugo /gohugo.sh -p config-docker.toml


deploy:
  name: "FOSS Team Deployment"
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  target_branch: master
  on:
    branch: develop
  fqdn: fossday.org
