sudo: required

services:
  - docker

before_install:
  - docker build -t fossday/gohugo .
  - docker run -it -v $(pwd)/site:/src -v $(pwd)/public:/src/public -p 1313:1313 fossday/gohugo /gohugo.sh -s

  deploy:
  provider: script
  script: docker run -it -v $(pwd)/site:/src -v $(pwd)/public:/src/public -p 1313:1313 fossday/gohugo
  on:
    branch: master