sudo: required

services:
  - docker

before_install:
- docker build -t fossday/gohugo .

script:
  - docker run --rm -v $(pwd)/site:/src -v $(pwd)/public:/src/public fossday/gohugo
  - echo $?

after_success:
- ls -la

deploy:
  name: FOSS Team Deployment
  provider: pages
  local_dir: site/public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  fqdn: fossday.org
  on:
    branch: master
