baseurl: "http://fossday.org"
title: "Primeiro Foss Day Lajeado"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "FossDay Lajeado"
  Description: "Conference description"
  Date: "5 de Maio de 2018"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Univates"
  Address: "UNIVATES"
  City:  "Lajeado"
  State: "Rio Grande do Sul"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyD0SXo4PtQAlft4ERHwSlsGjQ6RYyF20hc"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Sobre"
    location: "Local"
    speakers: "Palestrantes"
    schedule: "Grade"
    sponsors: "Patrocinadores"
    partners: "Parceiros"
    contact: "Contato"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Faça seu registro!"
    link: "https://goo.gl/wtmEEE"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/fossday/site"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Recepção + Coffee"
      time: "08:30"

    - name: "Jon \"Maddog\" Hall"
      photo: "/img/speakers/maddog.png"
      bio: "Jon Maddog Hall é o diretor executivo da Linux International, uma organização sem fins lucrativos de profissionais da computação e CEO da OptDyn"
      company: "Linux Professional Institute (LPI)"
      link:
        href: "http://twitter.com/maddoghall"
        text: "@maddoghall"
      presentation:
        title: "Abertura do evento"
        description: "-"
        time: "09h00"

    - name: "Jon \"Maddog\" Hall"
      photo: "/img/speakers/maddog.png"
      bio: "Jon Maddog Hall é o diretor executivo da Linux International, uma organização sem fins lucrativos de profissionais da computação e CEO da OptDyn"
      company: "Linux Professional Institute (LPI)"
      link:
        href: "http://twitter.com/maddoghall"
        text: "@maddoghall"
      presentation:
        title: "Computação em nuvem, Criptomoedas e Blockchain"
        description: ""
        time: "09h10"

    - name: "Rafael Dutra"
      photo: "/img/speakers/rafael_dutra.jpg"
      bio: "Rafael Dutra é Administrador de Sistemas e entusiasta DevOps. Utiliza Linux desde 2005 e atualmente trabalha como Arquiteto SAAS para Jive Software pela Crossover"
      company: "Crossover/Jive Software"
      link:
        href: "http://rafaeldutra.me"
        text: "@raffaeldutra"
      presentation:
        title: "Docker Workshop (iniciante e intermediário)"
        description: "Um hands on para iniciarmos no mundo de containers utilizando Docker"
        time: "11h00"

    - name: "Almoço"
      time: "12h00"

    - name: "Rafael Dutra"
      photo: "/img/speakers/rafael_dutra.jpg"
      bio: "Rafael Dutra é Administrador de Sistemas e entusiasta DevOps. Utiliza Linux desde 2005 e atualmente trabalha como Arquiteto SAAS para Jive Software pela Crossover"
      company: "Crossover/Jive Software"
      link:
        href: "http://rafaeldutra.me"
        text: "@raffaeldutra"
      presentation:
        title: "Docker Workshop (iniciante e intermediário)"
        description: "Continuação do Workshop sobre Docker"
        time: "13h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Pablo Dall'Oglio"
      photo: "/img/speakers/pablo.jpeg"
      bio: "Pablo Dall’Oglio é graduado em Análise de Sistemas e mestre em Engenharia de Software pela Universidade do Vale do Rio dos Sinos (Unisinos). Autor dos livros PHP-GTK – Criando aplicações gráficas com PHP e Criando relatórios com PHP, tem grande experiência no desenvolvimento de sistemas para gestão de negócios e está constantemente envolvido com projeto e implementação de softwares orientados a objetos.Atualmente dedica-se à sua empresa, a Adianti Solutions (adianti.com.br), onde constrói ferramentas de produtividade como o Adianti Framework (adianti.com.br/framework) e o Adianti Reports (adianti.com.br/reports), além de prestar consultoria em projeto e desenvolvimento de sistemas orientados a objetos."
      company: "Adianti Solutions"
      link:
        href: "https://www.adianti.com.br/"
        text: "https://www.adianti.com.br/"
      presentation:
        title: ""
        description: ""
        time: "15h30"

    - name: "Encerramento"
      time: "17:00"
